# Generated by Django 5.2 on 2026-05-22 02:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('vendedor', 'Vendedor'), ('contador', 'Contador')], default='vendedor', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='facturacion.categoria')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('rif', 'RIF'), ('cedula', 'Cédula'), ('pasaporte', 'Pasaporte')], max_length=20)),
                ('numero_documento', models.CharField(max_length=20)),
                ('nombre_razon_social', models.CharField(max_length=200)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'indexes': [models.Index(fields=['tipo_documento', 'numero_documento'], name='facturacion_tipo_do_d6b35c_idx'), models.Index(fields=['nombre_razon_social'], name='facturacion_nombre__b6346c_idx')],
                'unique_together': {('tipo_documento', 'numero_documento')},
            },
        ),
        migrations.CreateModel(
            name='CabeceraFactura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_factura', models.CharField(max_length=20, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('tipo_documento', models.CharField(choices=[('factura', 'Factura'), ('nota_debito', 'Nota de Débito'), ('nota_credito', 'Nota de Crédito')], max_length=20)),
                ('estatus', models.CharField(choices=[('borrador', 'Borrador'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20)),
                ('tasa_cambio', models.DecimalField(decimal_places=4, max_digits=10)),
                ('moneda_principal', models.CharField(choices=[('bs', 'Bolívares'), ('usd', 'Dólares')], max_length=3)),
                ('subtotal_bs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('subtotal_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('monto_iva_bs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('monto_iva_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('descuento_bs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('descuento_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_bs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('numero_control', models.CharField(blank=True, max_length=20)),
                ('serie', models.CharField(blank=True, max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='facturacion.cliente')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_bs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_bs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=0)),
                ('permite_stock_negativo', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='facturacion.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario_bs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal_bs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_iva_bs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_iva_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_bs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cabecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.cabecerafactura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='facturacion.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['email'], name='facturacion_email_2ef2b6_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['username'], name='facturacion_usernam_990795_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol'], name='facturacion_rol_5fe278_idx'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['nombre'], name='facturacion_nombre_d4ceb0_idx'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['categoria_padre'], name='facturacion_categor_52fd8e_idx'),
        ),
        migrations.AddIndex(
            model_name='cabecerafactura',
            index=models.Index(fields=['numero_factura'], name='facturacion_numero__570a50_idx'),
        ),
        migrations.AddIndex(
            model_name='cabecerafactura',
            index=models.Index(fields=['cliente'], name='facturacion_cliente_7b0814_idx'),
        ),
        migrations.AddIndex(
            model_name='cabecerafactura',
            index=models.Index(fields=['usuario'], name='facturacion_usuario_dcfd28_idx'),
        ),
        migrations.AddIndex(
            model_name='cabecerafactura',
            index=models.Index(fields=['fecha_emision'], name='facturacion_fecha_e_899707_idx'),
        ),
        migrations.AddIndex(
            model_name='cabecerafactura',
            index=models.Index(fields=['estatus'], name='facturacion_estatus_a6b29b_idx'),
        ),
        migrations.AddIndex(
            model_name='cabecerafactura',
            index=models.Index(fields=['tipo_documento'], name='facturacion_tipo_do_c7a170_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo'], name='facturacion_codigo_c125a1_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='facturacion_nombre_083299_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria'], name='facturacion_categor_9b89bc_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['stock_actual'], name='facturacion_stock_a_84c7c6_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleventa',
            index=models.Index(fields=['cabecera'], name='facturacion_cabecer_7495a2_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleventa',
            index=models.Index(fields=['producto'], name='facturacion_product_c614ab_idx'),
        ),
    ]
