# Generated by Django 5.2 on 2026-05-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabecerafactura',
            options={'permissions': [('view_report', 'Puede ver reportes de ventas')], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
    ]
