# Generated by Django 5.2 on 2026-09-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_alter_cabecerafactura_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('vendedor', 'Vendedor')], default='vendedor', max_length=20),
        ),
    ]
