# Generated by Django 5.2 on 2026-09-29 03:43

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_cabecerafactura_user_creation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoCaja',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Inicial (Fondo de Caja)')),
                ('monto_efectivo_sistema', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Efectivo Sistema')),
                ('monto_tarjeta_sistema', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Tarjeta Sistema')),
                ('efectivo_declarado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Efectivo Declarado')),
                ('tarjeta_declarada', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tarjeta Declarada')),
                ('diferencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Diferencia Total')),
                ('estatus', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=10, verbose_name='Estatus')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos_caja', to=settings.AUTH_USER_MODEL, verbose_name='Cajero')),
            ],
            options={
                'verbose_name': 'Turno de Caja',
                'verbose_name_plural': 'Turnos de Caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.AddField(
            model_name='cabecerafactura',
            name='turno_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='facturacion.turnocaja', verbose_name='Turno de Caja'),
        ),
        migrations.AddIndex(
            model_name='turnocaja',
            index=models.Index(fields=['cajero'], name='facturacion_cajero__698983_idx'),
        ),
        migrations.AddIndex(
            model_name='turnocaja',
            index=models.Index(fields=['estatus'], name='facturacion_estatus_938df1_idx'),
        ),
        migrations.AddIndex(
            model_name='turnocaja',
            index=models.Index(fields=['fecha_apertura'], name='facturacion_fecha_a_ea8e41_idx'),
        ),
    ]
