# Generated by Django 5.2 on 2026-10-02 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_turnocaja_cabecerafactura_turno_caja_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turnocaja',
            options={'ordering': ['-fecha_apertura'], 'permissions': [('view_turnocaja_audit', 'Puede ver auditoría de turnos de caja'), ('export_turnocaja_audit', 'Puede exportar reportes de turnos de caja')], 'verbose_name': 'Turno de Caja', 'verbose_name_plural': 'Turnos de Caja'},
        ),
    ]
